In [2]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[ 1.  2.  3.]


In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array([2.0, 4.0, 6.0])
x + y

array([ 3.,  6.,  9.])

In [6]:
x - y

array([-1., -2., -3.])

In [7]:
x / y

array([ 0.5,  0.5,  0.5])

In [8]:
x/2.0

array([ 0.5,  1. ,  1.5])

In [11]:
A = np.array([[1.0, 2.0], [3,4]])

In [12]:
print(A)

[[ 1.  2.]
 [ 3.  4.]]


In [13]:
A.shape

(2, 2)

In [14]:
A.dtype

dtype('float64')

In [15]:
B = np.array([[3,0],[0,6]])
A+B

array([[  4.,   2.],
       [  3.,  10.]])

In [16]:
A*B

array([[  3.,   0.],
       [  0.,  24.]])

In [17]:
print(A)

[[ 1.  2.]
 [ 3.  4.]]


In [18]:
A*10

array([[ 10.,  20.],
       [ 30.,  40.]])

In [21]:
A=np.array([[1,2], [3,4]])
B=np.array([10, 20])

In [22]:
A * B

array([[10, 40],
       [30, 80]])

In [24]:
X = np.array([[51, 55], [14,19], [0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [25]:
X[0]

array([51, 55])

In [26]:
X[0][1]

55

In [27]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [28]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [29]:
X > 15

array([ True,  True, False,  True, False, False], dtype=bool)

In [30]:
X[X > 15]

array([51, 55, 19])